package com.example.dsavisualizer;

import android.app.Activity;
import android.widget.Button;
import android.widget.TextView;
import android.widget.LinearLayout;

import java.util.ArrayList;

public class storage {
    private final Activity activity;
    public storage(Activity activity) {
        this.activity = activity;
    }

    public ArrayList<TextView> getTempRight(){
        ArrayList<TextView> buttons = new ArrayList<>();

        TextView b1 = activity.findViewById(R.id.rightB1);
        TextView b2 = activity.findViewById(R.id.rightB2);
        TextView b3 = activity.findViewById(R.id.rightB3);
        TextView b4 = activity.findViewById(R.id.rightB4);
        TextView b5 = activity.findViewById(R.id.rightB5);
        TextView b6 = activity.findViewById(R.id.rightB6);
        TextView b7 = activity.findViewById(R.id.rightB7);
        TextView b8 = activity.findViewById(R.id.rightB8);
        TextView b9 = activity.findViewById(R.id.rightB9);
        TextView b10 = activity.findViewById(R.id.rightB10);
        TextView b11 = activity.findViewById(R.id.rightB11);
        TextView b12 = activity.findViewById(R.id.rightB12);
        TextView b13 = activity.findViewById(R.id.rightB13);
        TextView b14 = activity.findViewById(R.id.rightB14);
        TextView b15 = activity.findViewById(R.id.rightB15);
        TextView b16 = activity.findViewById(R.id.rightB16);
        TextView b17 = activity.findViewById(R.id.rightB17);
        TextView b18 = activity.findViewById(R.id.rightB18);
        TextView b19 = activity.findViewById(R.id.rightB19);
        TextView b20 = activity.findViewById(R.id.rightB20);
        TextView b21 = activity.findViewById(R.id.rightB21);
        TextView b22 = activity.findViewById(R.id.rightB22);
        TextView b23 = activity.findViewById(R.id.rightB23);
        TextView b24 = activity.findViewById(R.id.rightB24);
        TextView b25 = activity.findViewById(R.id.rightB25);

        buttons.add(b1);
        buttons.add(b2);
        buttons.add(b3);
        buttons.add(b4);
        buttons.add(b5);
        buttons.add(b6);
        buttons.add(b7);
        buttons.add(b8);
        buttons.add(b9);
        buttons.add(b10);
        buttons.add(b11);
        buttons.add(b12);
        buttons.add(b13);
        buttons.add(b14);
        buttons.add(b15);
        buttons.add(b16);
        buttons.add(b17);
        buttons.add(b18);
        buttons.add(b19);
        buttons.add(b20);
        buttons.add(b21);
        buttons.add(b22);
        buttons.add(b23);
        buttons.add(b24);
        buttons.add(b25);
        return buttons;
    }
    public ArrayList<TextView> getTempLeft(){
        ArrayList<TextView> buttons = new ArrayList<>();

        TextView b1 = activity.findViewById(R.id.leftB1);
        TextView b2 = activity.findViewById(R.id.leftB2);
        TextView b3 = activity.findViewById(R.id.leftB3);
        TextView b4 = activity.findViewById(R.id.leftB4);
        TextView b5 = activity.findViewById(R.id.leftB5);
        TextView b6 = activity.findViewById(R.id.leftB6);
        TextView b7 = activity.findViewById(R.id.leftB7);
        TextView b8 = activity.findViewById(R.id.leftB8);
        TextView b9 = activity.findViewById(R.id.leftB9);
        TextView b10 = activity.findViewById(R.id.leftB10);
        TextView b11 = activity.findViewById(R.id.leftB11);
        TextView b12 = activity.findViewById(R.id.leftB12);
        TextView b13 = activity.findViewById(R.id.leftB13);
        TextView b14 = activity.findViewById(R.id.leftB14);
        TextView b15 = activity.findViewById(R.id.leftB15);
        TextView b16 = activity.findViewById(R.id.leftB16);
        TextView b17 = activity.findViewById(R.id.leftB17);
        TextView b18 = activity.findViewById(R.id.leftB18);
        TextView b19 = activity.findViewById(R.id.leftB19);
        TextView b20 = activity.findViewById(R.id.leftB20);
        TextView b21 = activity.findViewById(R.id.leftB21);
        TextView b22 = activity.findViewById(R.id.leftB22);
        TextView b23 = activity.findViewById(R.id.leftB23);
        TextView b24 = activity.findViewById(R.id.leftB24);
        TextView b25 = activity.findViewById(R.id.leftB25);

        buttons.add(b1);
        buttons.add(b2);
        buttons.add(b3);
        buttons.add(b4);
        buttons.add(b5);
        buttons.add(b6);
        buttons.add(b7);
        buttons.add(b8);
        buttons.add(b9);
        buttons.add(b10);
        buttons.add(b11);
        buttons.add(b12);
        buttons.add(b13);
        buttons.add(b14);
        buttons.add(b15);
        buttons.add(b16);
        buttons.add(b17);
        buttons.add(b18);
        buttons.add(b19);
        buttons.add(b20);
        buttons.add(b21);
        buttons.add(b22);
        buttons.add(b23);
        buttons.add(b24);
        buttons.add(b25);
        return buttons;
    }
    public ArrayList<LinearLayout> getLayouts(){
        ArrayList<LinearLayout> layouts = new ArrayList<>();
        LinearLayout l1 = activity.findViewById(R.id.l1);
        LinearLayout l2 = activity.findViewById(R.id.l2);
        LinearLayout l3 = activity.findViewById(R.id.l3);
        LinearLayout l4 = activity.findViewById(R.id.l4);
        LinearLayout l5 = activity.findViewById(R.id.l5);
        LinearLayout l6 = activity.findViewById(R.id.l6);
        LinearLayout l7 = activity.findViewById(R.id.l7);
        LinearLayout l8 = activity.findViewById(R.id.l8);
        LinearLayout l9 = activity.findViewById(R.id.l9);
        LinearLayout l10 = activity.findViewById(R.id.l10);
        LinearLayout l11 = activity.findViewById(R.id.l11);
        LinearLayout l12 = activity.findViewById(R.id.l12);
        LinearLayout l13 = activity.findViewById(R.id.l13);
        LinearLayout l14 = activity.findViewById(R.id.l14);
        LinearLayout l15 = activity.findViewById(R.id.l15);
        LinearLayout l16 = activity.findViewById(R.id.l16);
        LinearLayout l17 = activity.findViewById(R.id.l17);
        LinearLayout l18 = activity.findViewById(R.id.l18);
        LinearLayout l19 = activity.findViewById(R.id.l19);
        LinearLayout l20 = activity.findViewById(R.id.l20);
        LinearLayout l21 = activity.findViewById(R.id.l21);
        LinearLayout l22 = activity.findViewById(R.id.l22);
        LinearLayout l23 = activity.findViewById(R.id.l23);
        LinearLayout l24 = activity.findViewById(R.id.l24);
        LinearLayout l25 = activity.findViewById(R.id.l25);
        LinearLayout l26 = activity.findViewById(R.id.l26);
        LinearLayout l27 = activity.findViewById(R.id.l27);
        LinearLayout l28 = activity.findViewById(R.id.l28);
        LinearLayout l29 = activity.findViewById(R.id.l29);
        LinearLayout l30 = activity.findViewById(R.id.l30);
        LinearLayout l31 = activity.findViewById(R.id.l31);
        LinearLayout l32 = activity.findViewById(R.id.l32);
        LinearLayout l33 = activity.findViewById(R.id.l33);
        LinearLayout l34 = activity.findViewById(R.id.l34);
        LinearLayout l35 = activity.findViewById(R.id.l35);
        LinearLayout l36 = activity.findViewById(R.id.l36);
        LinearLayout l37 = activity.findViewById(R.id.l37);
        LinearLayout l38 = activity.findViewById(R.id.l38);
        LinearLayout l39 = activity.findViewById(R.id.l39);
        LinearLayout l40 = activity.findViewById(R.id.l40);
        LinearLayout l41 = activity.findViewById(R.id.l41);
        LinearLayout l42 = activity.findViewById(R.id.l42);
        LinearLayout l43 = activity.findViewById(R.id.l43);
        LinearLayout l44 = activity.findViewById(R.id.l44);
        LinearLayout l45 = activity.findViewById(R.id.l45);
        LinearLayout l46 = activity.findViewById(R.id.l46);
        LinearLayout l47 = activity.findViewById(R.id.l47);
        LinearLayout l48 = activity.findViewById(R.id.l48);
        LinearLayout l49 = activity.findViewById(R.id.l49);
        LinearLayout l50 = activity.findViewById(R.id.l50);

        layouts.add(l1);
        layouts.add(l2);
        layouts.add(l3);
        layouts.add(l4);
        layouts.add(l5);
        layouts.add(l6);
        layouts.add(l7);
        layouts.add(l8);
        layouts.add(l9);
        layouts.add(l10);
        layouts.add(l11);
        layouts.add(l12);
        layouts.add(l13);
        layouts.add(l14);
        layouts.add(l15);
        layouts.add(l16);
        layouts.add(l17);
        layouts.add(l18);
        layouts.add(l19);
        layouts.add(l20);
        layouts.add(l21);
        layouts.add(l22);
        layouts.add(l23);
        layouts.add(l24);
        layouts.add(l25);
        layouts.add(l26);
        layouts.add(l27);
        layouts.add(l28);
        layouts.add(l29);
        layouts.add(l30);
        layouts.add(l31);
        layouts.add(l32);
        layouts.add(l33);
        layouts.add(l34);
        layouts.add(l35);
        layouts.add(l36);
        layouts.add(l37);
        layouts.add(l38);
        layouts.add(l39);
        layouts.add(l40);
        layouts.add(l41);
        layouts.add(l42);
        layouts.add(l43);
        layouts.add(l44);
        layouts.add(l45);
        layouts.add(l46);
        layouts.add(l47);
        layouts.add(l48);
        layouts.add(l49);
        layouts.add(l50);

        return layouts;
    }

    public ArrayList<Button> getButtons(){
        ArrayList<Button> buttons = new ArrayList<>();

        Button b1 = activity.findViewById(R.id.button1);
        Button b2 = activity.findViewById(R.id.button2);
        Button b3 = activity.findViewById(R.id.button3);
        Button b4 = activity.findViewById(R.id.button4);
        Button b5 = activity.findViewById(R.id.button5);
        Button b6 = activity.findViewById(R.id.button6);
        Button b7 = activity.findViewById(R.id.button7);
        Button b8 = activity.findViewById(R.id.button8);
        Button b9 = activity.findViewById(R.id.button9);
        Button b10 = activity.findViewById(R.id.button10);
        Button b11 = activity.findViewById(R.id.button11);
        Button b12 = activity.findViewById(R.id.button12);
        Button b13 = activity.findViewById(R.id.button13);
        Button b14 = activity.findViewById(R.id.button14);
        Button b15 = activity.findViewById(R.id.button15);
        Button b16 = activity.findViewById(R.id.button16);
        Button b17 = activity.findViewById(R.id.button17);
        Button b18 = activity.findViewById(R.id.button18);
        Button b19 = activity.findViewById(R.id.button19);
        Button b20 = activity.findViewById(R.id.button20);
        Button b21 = activity.findViewById(R.id.button21);
        Button b22 = activity.findViewById(R.id.button22);
        Button b23 = activity.findViewById(R.id.button23);
        Button b24 = activity.findViewById(R.id.button24);
        Button b25 = activity.findViewById(R.id.button25);
        Button b26 = activity.findViewById(R.id.button26);
        Button b27 = activity.findViewById(R.id.button27);
        Button b28 = activity.findViewById(R.id.button28);
        Button b29 = activity.findViewById(R.id.button29);
        Button b30 = activity.findViewById(R.id.button30);
        Button b31 = activity.findViewById(R.id.button31);
        Button b32 = activity.findViewById(R.id.button32);
        Button b33 = activity.findViewById(R.id.button33);
        Button b34 = activity.findViewById(R.id.button34);
        Button b35 = activity.findViewById(R.id.button35);
        Button b36 = activity.findViewById(R.id.button36);
        Button b37 = activity.findViewById(R.id.button37);
        Button b38 = activity.findViewById(R.id.button38);
        Button b39 = activity.findViewById(R.id.button39);
        Button b40 = activity.findViewById(R.id.button40);
        Button b41 = activity.findViewById(R.id.button41);
        Button b42 = activity.findViewById(R.id.button42);
        Button b43 = activity.findViewById(R.id.button43);
        Button b44 = activity.findViewById(R.id.button44);
        Button b45 = activity.findViewById(R.id.button45);
        Button b46 = activity.findViewById(R.id.button46);
        Button b47 = activity.findViewById(R.id.button47);
        Button b48 = activity.findViewById(R.id.button48);
        Button b49 = activity.findViewById(R.id.button49);
        Button b50 = activity.findViewById(R.id.button50);

        buttons.add(b1);
        buttons.add(b2);
        buttons.add(b3);
        buttons.add(b4);
        buttons.add(b5);
        buttons.add(b6);
        buttons.add(b7);
        buttons.add(b8);
        buttons.add(b9);
        buttons.add(b10);
        buttons.add(b11);
        buttons.add(b12);
        buttons.add(b13);
        buttons.add(b14);
        buttons.add(b15);
        buttons.add(b16);
        buttons.add(b17);
        buttons.add(b18);
        buttons.add(b19);
        buttons.add(b20);
        buttons.add(b21);
        buttons.add(b22);
        buttons.add(b23);
        buttons.add(b24);
        buttons.add(b25);
        buttons.add(b26);
        buttons.add(b27);
        buttons.add(b28);
        buttons.add(b29);
        buttons.add(b30);
        buttons.add(b31);
        buttons.add(b32);
        buttons.add(b33);
        buttons.add(b34);
        buttons.add(b35);
        buttons.add(b36);
        buttons.add(b37);
        buttons.add(b38);
        buttons.add(b39);
        buttons.add(b40);
        buttons.add(b41);
        buttons.add(b42);
        buttons.add(b43);
        buttons.add(b44);
        buttons.add(b45);
        buttons.add(b46);
        buttons.add(b47);
        buttons.add(b48);
        buttons.add(b49);
        buttons.add(b50);

        return buttons;
    }

}
